# Generated by Django 3.1.5 on 2021-01-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driveManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Observations',
            new_name='Observation',
        ),
    ]
